--- #YAML:1.0
name:                Continuity-REPL
version:             0.01
abstract:            Use a Devel::REPL on a Continuity server
license:             Perl
author:              
    - Brock Wilcox <awwaiid@thelackthereof.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Continuity:                    0.991
    Devel::REPL:                   1.002001
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
